### ISSUE TITLE
Unzip Error

### ISSUE THREAD

**Issue by GolamRabbany123** [tomwiggers/Magisk-ConCal-Sync-MicroG#1]
I downloaded the repo as zip .
Then unzipped the repo and Changed the file structure as mentioned. But magisk is saying unzip error.
![Screenshot_20210508-072740855](https://user-images.githubusercontent.com/43527678/117521340-0e6c4600-afcf-11eb-8905-a43947cef554.jpg)

Unzip  error

**Comment by GolamRabbany123** [comment]
Help .

I kept the file structure as mentioned. But when I flash the module it says Unzip Error.

**Comment by tomwiggers** [comment]
Hi, I doubt it is still relevant, but considering the file name of the README is different I am under the impression you might have changed something.

I would advice to just clone the repo to your computer and zip the folder contents (I think you should not use any advanced compression methods, maybe try to select zipping without compression if possible).

I will close this now, feel free to re-open if you keep having this issue, I will try to reply a bit faster. :)
