### ISSUE TITLE
Bootloop - Lineage for microG + Magisk

### ISSUE THREAD

**Issue by timabell** [tomwiggers/Magisk-ConCal-Sync-MicroG#3]
I'm afraid I don't have any details on why yet, if I get them I'll add them but rebooting after installing the module has caused the phone to fail to boot and drop to the lineage recovery "try again?" screen. :cry: 

Every last detail of my work in progress setup is documented here: <https://timwise.co.uk/2021/12/17/phone-setup-notes/>

I'll post any more details I can find as comments for the benefit of others.

**Comment by timabell** [comment]
Bootloop log from `logcat`, no idea if this is useful, doesn't mean much to me: [concal-bootloop-logcat1.txt.gz](https://github.com/tomwiggers/Magisk-ConCal-Sync-MicroG/files/8693772/concal-bootloop-logcat1.txt.gz)

Looks to me that the logs pretty much start repeating at some point.

I let this run for longer another time and it got to 133Mb and was still going strong when I killed it.

**Comment by tomwiggers** [comment]
Hi, thank you for posting. I have read through the logcat but it's too much information to go through, it would requite some more investigation.

I did not make any effort in this module to support anything other than the device I am/was using at the time. This is an arm64 device.

The only obvious reason I can think of is that you used the module on a device based on a different architecture.
